### ISSUE TITLE
افزودن disable به date time picker و date picker

### ISSUE THREAD

**Issue by AmirMohammadDehghan** [4xmen/lput#1]
درود! 
اگر امکانش هست ویژگی دیسیبل را به date time picker و date picker اضافه کنید 
به این نحو که اول بتوان یک یا چندین تاریخ خاص را دیسیبل کرد
یک یا چند هفته خاص را دیسیبل کرد
یک یا چند بازه زمانی را دیسیبل کرد
یک یا چند ماه را دیسیبل کرد

زیرا این سیستم برای پلتفرم های نوبت دهی بسیار مهم است که بتوانند روز هایی که نوبت پر شده را غیر قابل انتخاب کنند
و نکته آخر دیسیبل شدن بعد از رندر شدن صفحه هم قابل کنترل باشد که بتوانیم برای مثال بعد از انتخاب چند فیلد توسط کاربر با api و برای مثال Ajax برسی کنیم و طبق آن یکسری روز را دیسیبل کنیم

سپاس فراوان از تیم شما

**Comment by A1Gard** [comment]
الان xmax و xmin  اضافه شد تا بازه رو بشه کنترل کرد حداقل و حداکثر قابل جایگزین شد، برای disable کردن چند گزینه به نظرم یه issue جدید باز در مورددش بحث و تبادل نظر کنیم ببینیم چطور درستش کنیم
![image](https://github.com/4xmen/lput/assets/9222481/fc74fbb8-dc8a-49a2-b3b4-036917504c17)
![image](https://github.com/4xmen/lput/assets/9222481/9ea09066-c9e9-40db-aa24-a26981872a19)


c6a6d44f52ca9d

**Comment by AmirMohammadDehghan** [comment]
باشه حتما
